name: "godot gut test"
on: push

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker test
        uses: ceceppa/godot-gut-ci@main
        with:
          godot_version: 4.1.1 # uses godot 3.2.1
          gut_params: -gtest=test_build/tests/unit -gdir=res://tests -gsuffix=.gd -gconfig=test_build/.gutconfig.json -ginclude_subdirs=true
