
name: "godot gut test"
on:
  push:
    branches: ['main']
    paths: 
      - 'test_build/**'
  pull_request:
    branches: ['main']
    paths: 
      - 'test_build/**'
    
  workflow_dispatch:

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker test
        uses: ceceppa/godot-gut-ci@master
        with:
          godot_version: 4.1.1
          gut_params: -gdir=res://tests/unit/
