
name: Godot Unit Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Godot
      uses: ceceppa/godot-gut-ci@main
      with:
        godot_version: '4.1.1'
        project_path: 'test_build'

    - name: Run Unit Tests
      run: godot -s "addons/Gut/gut_cmdln.gd" --path "test_build" --exit
