name: "godot gut test"
on: push

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Run GUT Tests
        # You may pin to the exact commit or the version.
        # uses: yeslayla/run-gut-tests-action@db0ad0d03b25a56ca0a5911e45ebb365a1a267bd
        uses: yeslayla/run-gut-tests-action@v1.0.1
        with:
          # The container to run tests inside of.
          containerImage: barichello/godot-ci:latest # optional, default is barichello/godot-ci:latest
          # The name directory to run tests in.
          directory: test_build # optional
